In [1]:
import pandas as pd
import sklearn as sk
import numpy as np
import tensorflow as tf
import os
from keras import regularizers
from keras.callbacks import Callback
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.linear_model import LogisticRegression
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [2]:
paths = []
for i, _, j in os.walk('./titanic/'):
    for filename in j:
        paths.append(os.path.join(i, filename))
print(paths)

['./titanic/gender_submission.csv', './titanic/test.csv', './titanic/train.csv']


In [4]:
tr = pd.read_csv(paths[2])
te = pd.read_csv(paths[1])
gs = pd.read_csv(paths[0])
# print(tr.head(4))
# print(gs.head(4))

In [5]:
# ind = np.where(tr['Sex'][:] == 'female')
# ind = ind[0]
# ind = ind.tolist()
# print(ind)
# tr.loc[ind, 'Sex'] = 0
# print(tr.head())
tr['Sex'] = tr['Sex'] == 'male'
tr['Sex'] = tr['Sex'].astype(int)
# print(tr.head(10))
te['Sex'] = te['Sex'] == 'male'
te['Sex'] = te['Sex'].astype(int)
ind = np.where(tr['Embarked'] == 'S')
ind = ind[0].tolist()
tr.loc[ind, 'Embarked'] = 0
print(len(ind))
ind = np.where(tr['Embarked'] == 'Q')[0].tolist()
tr.loc[ind, 'Embarked'] = 1
print(len(ind))
ind = np.where(tr['Embarked'] == 'C')[0].tolist()
tr.loc[ind, 'Embarked'] = 2
print(len(ind))
ind = np.where(te['Embarked'] == 'S')
ind = ind[0].tolist()
te.loc[ind, 'Embarked'] = 0
ind = np.where(te['Embarked'] == 'Q')[0].tolist()
te.loc[ind, 'Embarked'] = 1
ind = np.where(te['Embarked'] == 'C')[0].tolist()
te.loc[ind, 'Embarked'] = 2
# print(tr.head(10))

644
77
168


In [6]:
# ind = np.where(tr.Age <= 12)
# tr.loc[ind[0], 'Age'] = 0
# ind = np.where((tr.Age>12) & (tr.Age<= 18))
# tr.loc[ind[0], 'Age'] = 1
# ind = np.where((tr.Age>18) & (tr.Age<=35))
# tr.loc[ind[0], 'Age'] = 2
# ind = np.where((tr.Age>35))
# tr.loc[ind[0], 'Age'] = 3
# ind = np.where(tr.Age.isnull())
# print(ind)
# tr.loc[ind[0], 'Age'] = tr.Age.mode()[0]
# print(np.where((tr.Age == 2)))
# print(tr.shape)
# print(tr[['Survived', 'Age']].head(20))


# ind = np.where(te.Age <= 12)
# te.loc[ind[0], 'Age'] = 0
# ind = np.where((te.Age>12) & (te.Age<= 18))
# te.loc[ind[0], 'Age'] = 1
# ind = np.where((te.Age>18) & (te.Age<=35))
# te.loc[ind[0], 'Age'] = 2
# ind = np.where((te.Age>35))
# te.loc[ind[0], 'Age'] = 3
# ind = np.where(te.Age.isnull())
# print(ind)
# te.loc[ind[0], 'Age'] = te.Age.mode()[0]
# print(np.where((te.Age == 2)))
# print(te.shape)
# print(te[['Age']].head(20))

In [7]:
# tr.Parch = tr.Parch.fillna(tr.Parch.mode()[0], inplace = True)
print(np.where(tr.Parch.isnull()))
print(np.where(te.Parch.isnull()))

(array([], dtype=int64),)
(array([], dtype=int64),)


In [8]:
# print(np.sum(tr['Embarked'].isnull().to_numpy().astype(int)))
# print(np.where(tr['Embarked'].isnull()))
# tr.loc[61, 'Embarked'] = 0
# tr.loc[891, 'Embarked'] = 0

# tr['Embarked'].fillna(tr['Embarked'].mode, inplace = True)
# te['Embarked'].fillna(tr.Embarked.mode(), inplace = True)
# pd.get_dummies(tr.Embarked)

In [8]:
n = np.where(tr['Pclass'].isnull())[0]
print(n)
# print(n)
# print(tr.Pclass.mode())
for i in n:
    tr.loc[i, 'Pclass'] = tr['Pclass'].mode()[0]
n = np.where(tr['Pclass'].isnull())[0]
print(n)
n = np.where(tr['Pclass'].isnull())[0]
print(n)
# print(n)
# print(tr.Pclass.mode())
n = np.where(te['Pclass'].isnull())[0]
for i in n:
    te.loc[i, 'Pclass'] = te['Pclass'].mode()[0]

[]
[]
[]


In [9]:
n = np.where(tr['Embarked'].isnull())[0]
for i in n:
    tr.loc[i, 'Embarked'] = tr['Embarked'].mode()[0]
n = np.where(te['Embarked'].isnull())[0]
for i in n:
    te.loc[i, 'Embarked'] = te['Embarked'].mode()[0]

In [10]:
n = np.where(tr.Sex.isnull())[0]
for i in n:
    tr.loc[i, 'Sex'] = tr.Sex.mode()[0]
n = np.where(te.Sex.isnull())[0]
for i in n:
    te.loc[i, 'Sex'] = te.Sex.mode()[0]

In [11]:
n = np.where(tr.Fare.isnull())[0]
print(n)
for i in n:
    tr.loc[i, 'Fare'] = tr.Fare.median()
n = np.where(te.Fare.isnull())[0]
for i in n:
    te.loc[i, 'Fare'] = te.Fare.median()
print(tr.Fare.median())

[]
14.4542


In [12]:
print(te.skew())
tr.skew()

PassengerId    0.000000
Pclass        -0.534170
Sex           -0.568991
Age            0.457361
SibSp          4.168337
Parch          4.654462
Fare           3.692299
Embarked       0.873825
Survived       0.568991
dtype: float64


C:\Users\acer\AppData\Local\Temp\ipykernel_10312\2706224622.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  print(te.skew())
C:\Users\acer\AppData\Local\Temp\ipykernel_10312\2706224622.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  tr.skew()


PassengerId    0.000000
Survived       0.478523
Pclass        -0.630548
Sex           -0.618921
Age            0.389108
SibSp          3.695352
Parch          2.749117
Fare           4.787317
Embarked       1.264823
dtype: float64

In [13]:
tr.Fare = np.sqrt(tr.Fare)
te.Fare = np.sqrt(tr.Fare)

In [14]:
print(te.skew())
tr.skew()

PassengerId    0.000000
Pclass        -0.534170
Sex           -0.568991
Age            0.457361
SibSp          4.168337
Parch          4.654462
Fare           0.640724
Embarked       0.873825
Survived       0.568991
dtype: float64


C:\Users\acer\AppData\Local\Temp\ipykernel_10312\2706224622.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  print(te.skew())
C:\Users\acer\AppData\Local\Temp\ipykernel_10312\2706224622.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  tr.skew()


PassengerId    0.000000
Survived       0.478523
Pclass        -0.630548
Sex           -0.618921
Age            0.389108
SibSp          3.695352
Parch          2.749117
Fare           2.085004
Embarked       1.264823
dtype: float64

In [15]:
print(tr.corr())

             PassengerId  Survived    Pclass       Sex       Age     SibSp  \
PassengerId     1.000000 -0.005007 -0.035144  0.042939  0.036847 -0.057527   
Survived       -0.005007  1.000000 -0.338481 -0.543351 -0.077221 -0.035322   
Pclass         -0.035144 -0.338481  1.000000  0.131900 -0.369226  0.083081   
Sex             0.042939 -0.543351  0.131900  1.000000  0.093254 -0.114631   
Age             0.036847 -0.077221 -0.369226  0.093254  1.000000 -0.308247   
SibSp          -0.057527 -0.035322  0.083081 -0.114631 -0.308247  1.000000   
Parch          -0.001652  0.081629  0.018443 -0.245489 -0.189119  0.414838   
Fare            0.004035  0.312508 -0.660850 -0.237325  0.118042  0.257716   

                Parch      Fare  
PassengerId -0.001652  0.004035  
Survived     0.081629  0.312508  
Pclass       0.018443 -0.660850  
Sex         -0.245489 -0.237325  
Age         -0.189119  0.118042  
SibSp        0.414838  0.257716  
Parch        1.000000  0.290282  
Fare         0.290282  1.

In [16]:
trn = tr[['Pclass', 'Sex', 'Fare']].values
trl = tr[['Survived']].values
# trn, ten, trl, tel = train_test_split(trn, trl, test_size = 0.3)
test = te[['Pclass', 'Sex', 'Fare']].values
# tel = gs[['Survived']].values
# avg = (np.sum(trn, axis = 0)/trn.shape[0])
# print(avg)
# sigma = np.sqrt(np.sum(np.square(trn-avg))/trn.shape[0])
# trn[:, 2] = np.divide(np.subtract(trn[:, 2], avg[2]), sigma)

# avg = (np.sum(ten, axis = 0)/ten.shape[0])
# sigma = np.sqrt(np.sum(np.square(ten-avg))/ten.shape[0])
# ten[:, 2] = (ten[:, 2]-avg[2])/sigma

trn = trn.astype(np.float64)
# ten = ten.astype(np.float64)

print(trn.shape)
print(trl.shape)
# print(ten.shape)
# print(tel.shape)

(891, 3)
(891, 1)


In [17]:
print(trn)
print(trl)

[[3.         1.         2.6925824 ]
 [1.         0.         8.4429438 ]
 [3.         0.         2.81513765]
 ...
 [3.         0.         4.84252001]
 [1.         1.         5.47722558]
 [3.         1.         2.78388218]]
[[0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0

In [18]:
from sklearn.cluster import DBSCAN
dbs = DBSCAN(eps = 0.3, min_samples = 5)
ypd = dbs.fit_predict(trn)
print(ypd)

[ 0  1  2  3  0  0  4  0  2  5  2  6  0  0  2  7  0  8  2  2  9  8  2 10
  2  2  0 -1  2  0 10 11  2  8 12  4  0  0  2  2  2  5  0 -1  2  0  0  2
  0  2 13  0  1  5  4 10  7  0  5 -1  0  1 12  0 10  0  7  0  2  0  8 -1
 14  0 15  0  0  0  9  2  0  0  2  4  7  2  0  0 -1  0  0  0  4  0  0  0
 10  4  5  9  2  0 12  0  0  0  2  0  0  2  4  2  0  2  2  0  0 16 -1  2
 14  0  9  7 12  0  0  0  2  0  0  0  2  5  8  8  6  4  0 12  2  2  2  0
  8 17  0  2  9  8  8  1  0  0  0  4  2  0  0 -1  0  7  0  0 13  0  3  2
 10 15 10  0  2  0 10  0  0  6  8 -1 -1  8  0 17  2  4  2 10  0  0  7  8
  2  9  6 11  0  0  2  7  0 -1  0  0  0  2  0  0  2 10  0  5  0  8  0 18
  2  9  1  8  0  8  0  0 -1  0  8  0  8  2  1  0  8  2  8  2  9  5  8  8
  2  2  8  0  0 -1  2  7  4  9  0  2 10  0  2  2  1  1 -1  5  0  0 12 19
  2  8 13  0 11 20 10 -1  5 10  2  1  2 21  0  2  0  0  0  0 10  0  0  0
  8  2  1  1  8  2  0 10  0 11 10 -1  2  0 -1  7  0 -1 18 18  9  3  1 -1
  5  0  9  2  5  8 -1 20  0  0  7  5 -1 20  0  7  2

In [19]:
from sklearn.cluster import KMeans
kmm = KMeans(n_clusters = 2)
kmm_ypred = kmm.fit_predict(trn)
print(accuracy_score(kmm_ypred, trl))

0.6801346801346801


In [23]:
b = kmm.fit_predict(test)
print(b)

[0 0 1 0 0 0 0 1 0 0 0 1 1 1 1 1 1 0 0 0 1 0 1 1 1 0 1 0 1 0 1 1 0 0 1 0 0
 0 0 0 0 1 0 1 1 0 1 0 1 0 1 1 1 1 1 0 0 0 0 1 0 1 0 0 1 1 0 1 1 1 0 0 0 1
 1 1 0 1 1 0 0 1 1 0 1 0 0 0 0 1 0 0 1 0 1 0 1 0 0 0 1 1 0 0 0 0 0 0 0 1 1
 0 1 0 1 0 0 0 1 1 1 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 1 0 0 0 1 1 1 1 0 1 0
 1 1 1 0 0 0 0 0 1 0 1 0 0 0 1 0 1 0 1 0 1 0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 1
 1 1 0 0 1 1 1 0 1 1 0 1 0 1 0 0 0 1 1 1 1 0 1 1 0 0 0 1 1 0 1 0 1 1 0 1 0
 1 0 1 0 0 0 0 1 1 1 0 0 1 0 1 0 1 1 1 1 1 0 0 1 1 1 1 0 1 0 1 0 0 0 0 0 1
 0 0 0 1 0 1 0 1 0 0 0 1 0 1 0 0 1 1 1 1 1 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 0
 1 0 1 0 0 1 1 0 0 1 1 0 1 0 0 0 0 0 1 0 1 1 0 1 0 0 1 1 1 0 1 1 1 1 1 1 0
 0 0 1 1 0 1 0 1 0 0 1 0 0 1 0 1 1 1 1 1 1 0 1 1 0 0 0 0 1 1 0 1 0 0 0 1 1
 1 1 1 1 1 1 0 1 1 0 0 0 0 0 1 1 0 1 0 0 1 1 0 1 0 1 0 1 0 0 1 1 1 1 1 1 1
 1 0 0 0 1 0 0 1 0 0 0]


In [24]:
class myCallback(Callback):
    def on_epoch_end(self, epoch, logs = {}):
        if logs.get('accuracy') > 0.85:
            self.model.stop_training = True
callback = myCallback()
# earlyStopping = EarlyStopping(patience=100, monitor = 'accuracy', restore_best_weights = True)

In [ ]:
model_nn = tf.keras.Sequential([tf.keras.layers.Dense(256, activation = tf.nn.relu, kernel_regularizer = regularizers.l2(0.01)),
                                tf.keras.layers.Dropout(0.1),
                                tf.keras.layers.Dense(256, activation = tf.nn.tanh, kernel_regularizer = regularizers.l2(0.01)),
                                tf.keras.layers.Dropout(0.1),
                                tf.keras.layers.Dense(256, activation = tf.nn.tanh, kernel_regularizer = regularizers.l2(0.01)),
                                tf.keras.layers.Dense(1, activation = tf.nn.sigmoid)])
model_nn.compile(optimizer = tf.optimizers.RMSprop(learning_rate=0.01),
              loss = tf.losses.binary_crossentropy,
              metrics = ['accuracy'])
model_nn.fit(trn, trl, epochs = 500, callbacks = [callback])
model_nn.evaluate(ten, tel)

In [ ]:
def rounding_nn_BinaryPred(pred_nn = [[]]):
    for i in range(len(np.squeeze(pred_nn))):
        if pred_nn[i]<0.5:
            pred_nn[i] = np.floor(pred_nn[i])
        else:
            pred_nn[i] = np.ceil(pred_nn[i])

In [ ]:
y_pred_nn = model_nn.predict(ten)
rounding_nn_BinaryPred(y_pred_nn)
acc_nn = accuracy_score(y_pred_nn, tel)
tr_y_pred_nn = model_nn.predict(trn)
rounding_nn_BinaryPred(tr_y_pred_nn)
tr_acc_nn = accuracy_score(tr_y_pred_nn, trl)
print('accuracy on training set:', tr_acc_nn)
print('accuracy on test set:', acc_nn)
y_pred_nn = np.squeeze(y_pred_nn)
tr_y_pred_nn = np.squeeze(tr_y_pred_nn)

In [25]:
trl_knn = np.squeeze(trl)
model_knn = LogisticRegression()
model_knn.fit(trn, trl_knn)
# y_pred_knn = model_knn.predict(ten)
# acc_knn = accuracy_score(y_pred_knn, tel)
# tr_y_pred_knn = model_knn.predict(trn)
# tr_acc_knn = accuracy_score(tr_y_pred_knn, trl)
# print('accuracy on training set:', tr_acc_knn)
# print('accuracy on test set:', acc_knn)

LogisticRegression()

In [26]:

yp = model_knn.predict(test)


In [27]:
trl_knn = np.squeeze(trl)
model_knn = KNeighborsClassifier(n_neighbors = 3)
model_knn.fit(trn, trl_knn)
# y_pred_knn = model_knn.predict(ten)
# acc_knn = accuracy_score(y_pred_knn, tel)
# tr_y_pred_knn = model_knn.predict(trn)
# tr_acc_knn = accuracy_score(tr_y_pred_knn, trl)
# print('accuracy on training set:', tr_acc_knn)
# print('accuracy on test set:', acc_knn)

KNeighborsClassifier(n_neighbors=3)

In [28]:
yp1 = model_knn.predict(test)

In [29]:
trl_rf = np.squeeze(trl)
# tel_rf = np.squeeze(tel)
model_rf = RandomForestClassifier(n_estimators = 100, bootstrap = True)
model_rf.fit(trn, trl_rf)
# y_pred_rf = model_rf.predict(ten)
# tr_y_pred_rf = model_rf.predict(trn)
# acc_rf = accuracy_score(y_pred_rf, tel_rf)
# tr_acc_rf = accuracy_score(tr_y_pred_rf, trl)
# print('accuracy on training set:', tr_acc_rf)
# print('accuracy on test set:', acc_rf)

RandomForestClassifier()

In [30]:
yp2 = model_rf.predict(test)

In [ ]:
trn_gnb = np.array([trn[:, 2]]).reshape(trn.shape[0], 1)
ten_gnb = np.array([ten[:, 2]]).reshape(ten.shape[0], 1)
trl_nb = np.squeeze(trl)
tel_nb = np.squeeze(tel)
model_gnb = GaussianNB()
model_gnb.fit(trn_gnb, trl_nb)
y_pred_gnb = model_gnb.predict(ten_gnb)
tr_y_pred_gnb = model_gnb.predict(trn_gnb)
acc_gnb = accuracy_score(y_pred_gnb, tel_nb)
tr_acc_gnb = accuracy_score(tr_y_pred_gnb, trl_nb)
print('accuracy on training set:', tr_acc_gnb)
print('accuracy on test set:', acc_gnb)

In [ ]:
trn_mnb = tr[['Pclass']].values
print(trn_mnb.shape)
ten_mnb = te[['Pclass']].values
model_mnb = MultinomialNB()
model_mnb.fit(trn_mnb, trl_nb)
y_pred_mnb = model_mnb.predict(ten_mnb)
tr_y_pred_mnb = model_mnb.predict(trn_mnb)
acc_mnb = accuracy_score(y_pred_mnb, tel_nb)
tr_acc_mnb = accuracy_score(tr_y_pred_mnb, trl_nb)
print('accuracy on training set:', tr_acc_mnb)
print('accuracy on test set:', acc_mnb)

In [ ]:
trn_bnb = tr[['Sex']].values
ten_bnb = te[['Sex']].values
model_bnb = BernoulliNB()
model_bnb.fit(trn_bnb, trl_nb)
y_pred_bnb = model_bnb.predict(ten_bnb)
tr_y_pred_bnb = model_bnb.predict(trn_bnb)
acc_bnb = accuracy_score(y_pred_bnb, tel_nb)
tr_acc_bnb = accuracy_score(tr_y_pred_bnb, trl_nb)
print('accuracy on training set:', tr_acc_bnb)
print('accuracy on test set:', acc_bnb)

In [ ]:
y_pred_nb = (y_pred_bnb + y_pred_mnb + y_pred_gnb)/3
tr_y_pred_nb = (tr_y_pred_bnb + tr_y_pred_mnb + tr_y_pred_gnb)/3
for m in [y_pred_nb, tr_y_pred_nb]:
    for i in range(len(m)):
        if m[i]<0.5:
            m[i] = np.floor(m[i])
        else:
            m[i] = np.ceil(m[i])
acc_nb = accuracy_score(y_pred_nb, tel_nb)
tr_acc_nb = accuracy_score(tr_y_pred_nb, trl_nb)
print('accuracy on training set:', tr_acc_nb)
print('accuracy on test set:', acc_nb)

In [ ]:
# trl_rf = np.squeeze(trl)
# tel_rf = np.squeeze(tel)
# model_rf = svm.SVC(kernel = 'poly', degree = 4, C = 0.83)
# model_rf.fit(trn, trl_rf)
# y_pred_rf = model_rf.predict(ten)
# tr_y_pred_rf = model_rf.predict(trn)
# acc_rf = accuracy_score(y_pred_rf, tel_rf)
# print('accuracy on test set:', acc_rf)
# tr_acc_rf = accuracy_score(tr_y_pred_rf, trl)
# print('accuracy on training set:', tr_acc_rf)

In [ ]:
# model_rf.predict([[1, 1, 98.2, 0]])

In [31]:
trl_svm = np.squeeze(trl)
# tel_svm = np.squeeze(tel)
model_svm = svm.SVC(kernel = 'rbf', gamma = 0.5)
model_svm.fit(trn, trl_svm)
# y_pred_svm = model_svm.predict(ten)
# tr_y_pred_svm = model_svm.predict(trn)
# acc_svm = accuracy_score(y_pred_svm, tel_svm)
# tr_acc_svm = accuracy_score(tr_y_pred_svm, trl)
# print('accuracy on training set:', tr_acc_svm)
# print('accuracy on test set:', acc_svm)

SVC(gamma=0.5)

In [32]:
yp3 = model_svm.predict(test)

In [33]:
trl_gb = np.squeeze(trl)
# tel_gb = np.squeeze(tel)
model_gb = GradientBoostingClassifier(n_estimators=100, max_depth=2)
model_gb.fit(trn, trl_gb)
# y_pred_gb = model_gb.predict(ten)
# tr_y_pred_gb = model_gb.predict(trn)
# acc_gb = accuracy_score(y_pred_gb, tel_gb)
# tr_acc_gb = accuracy_score(tr_y_pred_gb, trl)
# print('accuracy on training set:', tr_acc_gb)
# print('accuracy on test set:', acc_gb)

GradientBoostingClassifier(max_depth=2)

In [34]:
yp4 = model_gb.predict(test)

In [47]:
trl_model = np.squeeze(trl)
# tel_model = np.squeeze(tel)
y_pred = ( b + yp + yp1 + yp3 + yp4 )/2
tr_y_pred = [1, 2] # (tr_y_pred_nn + tr_y_pred_knn + tr_y_pred_rf + tr_y_pred_svm + tr_y_pred_gb)/5
# for m in [y_pred, tr_y_pred]:
for i in range(len(y_pred)):
    if y_pred[i]<0.5:
        y_pred[i] = np.floor(y_pred[i])
    else:
        y_pred[i] = np.ceil(y_pred[i])
# acc = accuracy_score(y_pred, tel_model)
# tr_acc = accuracy_score(tr_y_pred, trl_model)
print(y_pred)
# print('accuracy on trainig set:', tr_acc)
# print('accuracy on test set:', acc)

[0. 1. 1. 0. 2. 0. 2. 1. 2. 0. 0. 1. 2. 1. 2. 3. 1. 0. 2. 2. 1. 0. 2. 1.
 2. 0. 2. 0. 1. 0. 1. 1. 2. 2. 1. 0. 2. 2. 0. 0. 0. 1. 0. 3. 2. 0. 1. 0.
 2. 2. 1. 1. 3. 2. 1. 0. 0. 0. 0. 2. 0. 1. 0. 2. 1. 3. 2. 1. 1. 2. 2. 0.
 1. 1. 3. 1. 0. 2. 1. 2. 0. 1. 1. 0. 1. 0. 2. 2. 2. 1. 2. 0. 3. 0. 1. 0.
 2. 0. 2. 0. 2. 1. 0. 0. 2. 0. 0. 0. 0. 1. 1. 2. 2. 2. 2. 0. 0. 2. 1. 3.
 3. 0. 2. 0. 0. 2. 0. 2. 1. 0. 0. 1. 2. 0. 0. 0. 0. 1. 2. 0. 2. 2. 1. 1.
 1. 0. 1. 0. 1. 1. 2. 0. 0. 2. 0. 0. 2. 2. 1. 1. 2. 0. 3. 0. 1. 2. 1. 0.
 2. 2. 0. 0. 0. 0. 0. 3. 3. 1. 3. 2. 1. 1. 2. 0. 2. 1. 3. 0. 2. 1. 1. 1.
 0. 1. 1. 1. 1. 2. 1. 2. 2. 0. 1. 3. 1. 1. 2. 1. 2. 0. 0. 0. 1. 3. 2. 1.
 2. 1. 3. 0. 3. 0. 3. 0. 3. 2. 0. 2. 0. 1. 1. 2. 0. 0. 1. 0. 1. 0. 3. 2.
 2. 3. 1. 0. 0. 1. 3. 1. 3. 2. 3. 0. 1. 0. 0. 0. 0. 0. 3. 0. 0. 0. 3. 1.
 1. 0. 1. 0. 2. 1. 1. 0. 2. 2. 0. 3. 1. 1. 1. 1. 2. 0. 2. 2. 2. 0. 0. 1.
 0. 0. 1. 1. 0. 1. 0. 0. 3. 1. 1. 0. 0. 1. 1. 0. 2. 3. 1. 0. 1. 2. 0. 0.
 0. 2. 2. 2. 1. 1. 0. 1. 0. 0. 1. 1. 3. 1. 2. 1. 1.

In [48]:
gs1 = gs.copy()
gs1['Survived1'] = b

In [49]:
gs1.to_csv('sub6.csv')